version: "3"

services:
  server:
    image: node:19.0.0-alpine
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/home/node

  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: